jobs:
- script: |
    multibranchPipelineJob('S3_static_website') {
        branchSources {
            git {
                id = 'configuration-as-code-s3'
                remote('https://github.com/IgorMishchuk/site-s3.git')
            }
        }
        configure { 
            it / disabled('true')
        }
    }